server:
  port: 80
spring:
  #数据库配置连接
  datasource:
    url: jdbc:mysql://database-qpj.cluster-cvk4uwiikfne.eu-north-1.rds.amazonaws.com:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: qpj
    password: quanquan52111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # DDL 级别 (create, create-drop, validate, update)
      ddl-auto: update
    show-sql: true
  data:
    redis:
      url: rediss://mycacheservless-slm8so.serverless.eun1.cache.amazonaws.com:6379
      lettuce:
        pool:
          max-active: 8  # 连接池最大连接数
          max-idle: 8    # 连接池中的最大空闲连接
          min-idle: 0    # 连接池中的最小空闲连接
        shutdown-timeout: 100  # 销毁连接池时的超时时间
        ssl: true